# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=255)),
                ('Author_Name', models.CharField(max_length=255)),
                ('Reader_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Rate', models.IntegerField()),
            ],
        ),
    ]
